server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: swagger-ui
          uri: lb://gateway
          predicates:
            - Path=/swagger-ui/index.html
          filters:
            - RedirectTo=302, /webjars/swagger-ui/index.html
        - id: swagger-config
          uri: lb://gateway
          predicates:
            - Path=/webjars/swagger-ui/${springdoc.api-docs.path}/swagger-config
          filters:
            - RewritePath=/webjars/swagger-ui/${springdoc.api-docs.path}/swagger-config, /v3/api-docs/swagger-config

springdoc.api-docs.path: ":-:"