server:
  port: 8080
spring:
  application:
    name: payment-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s